import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from '@tanstack/react-router';
import { useEffect, useState, type ReactNode } from 'react';
import appCss from '../styles.css?url';
import { supabase } from '@/integrations/supabase/client';

function NotFoundComponent(){return <div className="flex min-h-screen items-center justify-center px-4"><div className="text-center"><h1 className="text-7xl font-editorial">404</h1><p className="mt-3 text-muted-foreground">This page has moved on.</p><Link to="/" className="btn-outline mt-6 inline-flex">Return home</Link></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){const router=useRouter();return <div className="flex min-h-screen items-center justify-center px-4"><div className="max-w-md text-center"><h1 className="text-3xl font-editorial">Something went off-course</h1><p className="mt-2 text-sm text-muted-foreground">{error.message}</p><button onClick={()=>{router.invalidate();reset()}} className="btn-primary mt-5">Try again</button></div></div>}

export const Route = createRootRouteWithContext<{queryClient:QueryClient}>()({
  head:()=>({meta:[{charSet:'utf-8'},{name:'viewport',content:'width=device-width, initial-scale=1'},{title:'ApexAnchor — Marketplace'},{name:'description',content:'Buy, sell or rent homes, cars, land, office space, companies and business ideas — all in one marketplace.'}],links:[{rel:'stylesheet',href:appCss},{rel:'preconnect',href:'https://fonts.googleapis.com'},{rel:'preconnect',href:'https://fonts.gstatic.com',crossOrigin:'anonymous'},{rel:'stylesheet',href:'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&family=Inter:wght@400;500;600&display=swap'},{rel:'icon',href:`${import.meta.env.BASE_URL}favicon.ico`,type:'image/x-icon'}]}),
  shellComponent:({children}:{children:ReactNode})=><html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>,
  component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent,
});

function RootComponent(){const {queryClient}=Route.useRouteContext();const router=useRouter();const [user,setUser]=useState<{email?:string}|null>(null);
  useEffect(()=>{supabase.auth.getSession().then(({data})=>setUser(data.session?.user??null));const {data}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user??null);router.invalidate();if(session)queryClient.invalidateQueries()});return()=>data.subscription.unsubscribe()},[queryClient,router]);
  async function signOut(){await supabase.auth.signOut();queryClient.clear();router.navigate({to:'/',replace:true})}
  return <QueryClientProvider client={queryClient}><div className="min-h-screen flex flex-col"><header className="sticky top-0 z-40 border-b border-border/60 bg-background/85 backdrop-blur"><div className="max-w-6xl mx-auto px-5 min-h-16 flex items-center justify-between gap-4"><Link to="/" className="flex items-baseline gap-2 shrink-0"><span className="font-editorial text-2xl">ApexAnchor</span><span className="text-xs text-muted-foreground hidden sm:inline">— marketplace</span></Link><nav className="flex items-center gap-1 text-sm overflow-x-auto"><Link to="/browse" search={{kind:'sale'}} className="btn-ghost whitespace-nowrap">Browse to buy</Link><Link to="/browse" search={{kind:'rent'}} className="btn-ghost whitespace-nowrap">Browse to rent</Link><Link to="/broker/apexanchor" className="btn-ghost whitespace-nowrap">Broker channel</Link>{user?<><Link to="/deals" className="btn-ghost hidden md:inline-flex">Enquiries</Link><Link to="/dashboard" className="btn-ghost hidden md:inline-flex">Dashboard</Link><Link to="/sell" className="btn-primary whitespace-nowrap">List an asset</Link><button onClick={signOut} className="btn-ghost whitespace-nowrap">Sign out</button></>:<Link to="/auth" className="btn-ghost whitespace-nowrap">Sign in</Link>}</nav></div></header><main className="flex-1"><Outlet/></main><footer className="border-t border-border/60 mt-24"><div className="max-w-6xl mx-auto px-5 py-10 flex flex-col sm:flex-row gap-4 justify-between text-sm text-muted-foreground"><p className="font-editorial text-lg text-foreground">ApexAnchor</p><p>© {new Date().getFullYear()} ApexAnchor. Where buyers, sellers and renters meet.</p></div></footer></div></QueryClientProvider>;
}
