import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { z } from 'zod';
import { supabase } from '@/integrations/supabase/client';
import { BROKER_ADDRESS, BROKER_NAME, categoryLabel, formatPrice, type Kind } from '@/lib/marketplace';

export const Route=createFileRoute('/listings/$id')({component:ListingPage});
const schema=z.object({message:z.string().trim().min(5,'Tell us a little more').max(5000),offer:z.coerce.number().nonnegative().optional().or(z.literal('')),email:z.string().email().max(255).optional().or(z.literal('')),phone:z.string().max(40).optional().or(z.literal('')),start:z.string().optional(),end:z.string().optional()});
function ListingPage(){const {id}=Route.useParams();const nav=useNavigate();const {data:listing,isLoading,error}=useQuery({queryKey:['listing',id],queryFn:async()=>{const {data,error}=await supabase.from('listings').select('id,title,description,price,currency,kind,category,location,image_url,status').eq('id',id).maybeSingle();if(error)throw error;return data}});const [session,setSession]=useState<Awaited<ReturnType<typeof supabase.auth.getSession>>['data']['session']>(null);useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session))},[]);const [msg,setMsg]=useState(''),[offer,setOffer]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[sending,setSending]=useState(false),[err,setErr]=useState<string|null>(null);
async function submit(e:React.FormEvent){e.preventDefault();if(!session)return nav({to:'/auth'});setErr(null);const p=schema.safeParse({message:msg,offer:offer||'',email,phone,start,end});if(!p.success)return setErr(p.error.issues[0].message);const rental=listing?.kind==='rent';if(rental&&(!start||!end||end<=start))return setErr('Choose a valid start and end date.');setSending(true);const {data,error}=await supabase.rpc('create_buyer_deal',{p_listing:id,p_message:p.data.message,p_offer:typeof p.data.offer==='number'?p.data.offer:null,p_email:p.data.email||'',p_phone:p.data.phone||'',p_start:rental?start:null,p_end:rental?end:null});setSending(false);if(error||!data)return setErr(error?.message||'Could not create your private enquiry.');nav({to:'/deals/$id',params:{id:data}})}
if(isLoading)return <div className="max-w-5xl mx-auto px-5 py-16 text-muted-foreground">Loading…</div>;if(error||!listing)return <div className="max-w-5xl mx-auto px-5 py-16 text-center"><h1 className="font-editorial text-3xl">Listing not found</h1><Link to="/browse" search={{kind:'sale'}} className="btn-outline mt-6 inline-flex">Back to browse</Link></div>;const kind=listing.kind as Kind;
return <div className="max-w-5xl mx-auto px-5 py-12"><p className="eyebrow">{kind==='rent'?'For rent':'For sale'} · {categoryLabel(listing.category)}</p><h1 className="font-editorial text-5xl mt-2">{listing.title}</h1><p className="text-muted-foreground mt-1">{listing.location}</p><div className="grid md:grid-cols-3 gap-8 mt-8"><div className="md:col-span-2"><div className="aspect-[4/3] bg-muted rounded-md overflow-hidden">{listing.image_url?<img src={listing.image_url} alt={listing.title} className="w-full h-full object-cover"/>:<div className="h-full flex items-center justify-center text-muted-foreground">No image</div>}</div><h2 className="font-editorial text-2xl mt-8">About</h2><p className="mt-3 whitespace-pre-wrap leading-relaxed">{listing.description||'No description provided.'}</p><div className="card-warm p-6 mt-8"><p className="eyebrow">Verified broker channel</p><p className="mt-2 leading-relaxed">Send {BROKER_ADDRESS} your offer and any questions. The broker reviews it, confirms availability and gets back to you in one private thread.</p></div></div><aside className="space-y-5"><div className="card-warm p-6"><p className="field-label">{kind==='rent'?'Asking rent':'Asking price'}</p><p className="font-editorial text-3xl mt-1">{formatPrice(Number(listing.price),listing.currency,kind)}</p><div className="rule my-5"/><p className="field-label">Handled by</p><p className="mt-1">{BROKER_NAME}</p><p className="text-sm text-muted-foreground mt-1">Seller contact details are private.</p></div><div className="card-warm p-6"><h2 className="font-editorial text-2xl">{kind==='rent'?'Request these dates':'Make an offer'}</h2><form onSubmit={submit} className="mt-4 space-y-3">{kind==='rent'&&<div className="grid grid-cols-2 gap-2"><input type="date" className="input-field" value={start} onChange={e=>setStart(e.target.value)}/><input type="date" className="input-field" value={end} min={start||undefined} onChange={e=>setEnd(e.target.value)}/></div>}<input className="input-field" type="number" min="0" placeholder={`Optional offer (${listing.currency})`} value={offer} onChange={e=>setOffer(e.target.value)}/><textarea required className="input-field min-h-32" placeholder="Your message to ApexAnchor" value={msg} onChange={e=>setMsg(e.target.value)}/><input className="input-field" type="email" placeholder="Email (optional)" value={email} onChange={e=>setEmail(e.target.value)}/><input className="input-field" placeholder="Phone (optional)" value={phone} onChange={e=>setPhone(e.target.value)}/>{err&&<p className="text-sm text-destructive">{err}</p>}<button className="btn-primary w-full" disabled={sending}>{sending?'Opening private thread…':session?'Send privately':'Sign in to continue'}</button></form></div></aside></div></div>;
}
