import { createFileRoute, Link } from '@tanstack/react-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useIsBroker } from '@/hooks/useBroker';
import { BROKER_NAME, DEAL_STATUS_LABEL, categoryLabel, formatAmount, formatPrice, type DealStatus, type Kind } from '@/lib/marketplace';
export const Route=createFileRoute('/_authenticated/deals/$id')({component:DealThread});
const statuses:DealStatus[]=['open','negotiating','agreed','closed','declined'];
function DealThread(){const {id}=Route.useParams();const {user}=Route.useRouteContext();const qc=useQueryClient();const {data:isBroker}=useIsBroker(user.id);const {data:deal}=useQuery({queryKey:['deal',id],queryFn:async()=>{const {data,error}=await supabase.from('deals').select('id,listing_id,client_id,side,status,offer_amount,currency,contact_email,contact_phone,start_date,end_date,created_at,updated_at,listings(title,price,currency,kind,category,image_url,location)').eq('id',id).maybeSingle();if(error)throw error;return data}});const {data:messages}=useQuery({queryKey:['deal-messages',id],queryFn:async()=>{const {data,error}=await supabase.from('deal_messages').select('id,body,offer_amount,from_broker,sender_id,created_at').eq('deal_id',id).order('created_at');if(error)throw error;return data??[]}});useEffect(()=>{const channel=supabase.channel(`deal-${id}`).on('postgres_changes',{event:'*',schema:'public',table:'deal_messages',filter:`deal_id=eq.${id}`},()=>{qc.invalidateQueries({queryKey:['deal-messages',id]})}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'deals',filter:`id=eq.${id}`},()=>{qc.invalidateQueries({queryKey:['deal',id]})}).subscribe();return()=>{void supabase.removeChannel(channel)}},[id,qc]);const [body,setBody]=useState(''),[amount,setAmount]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState<string|null>(null);
async function send(e:React.FormEvent){e.preventDefault();if(!body.trim())return setErr('Write a message first.');setBusy(true);setErr(null);const offer=amount?Number(amount):null;const {error}=await supabase.from('deal_messages').insert({deal_id:id,sender_id:user.id,from_broker:!!isBroker,body:body.trim(),offer_amount:offer});if(!error&&offer!==null){await supabase.from('deals').update({offer_amount:offer}).eq('id',id)}setBusy(false);if(error)return setErr(error.message);setBody('');setAmount('');qc.invalidateQueries({queryKey:['deal-messages',id]});qc.invalidateQueries({queryKey:['deal',id]})}
async function setStatus(status:DealStatus){if(!isBroker)return;const {error}=await supabase.from('deals').update({status}).eq('id',id);if(error)setErr(error.message);else qc.invalidateQueries({queryKey:['deal',id]})}
if(!deal)return <div className="max-w-3xl mx-auto px-5 py-16 text-muted-foreground">Loading…</div>;const listing=(deal as any).listings as {title:string;price:number;currency:string;kind:string;category:string;image_url:string|null;location:string}|null;
return <div className="max-w-3xl mx-auto px-5 py-12"><Link to="/deals" className="text-sm underline">← All enquiries</Link><div className="card-warm p-5 mt-4 flex gap-4">{listing?.image_url&&<img src={listing.image_url} alt="" className="w-24 h-20 object-cover rounded"/>}<div><p className="eyebrow">{deal.side==='sell'?'Selling':'Buying'} · {DEAL_STATUS_LABEL[deal.status as DealStatus]}</p><h1 className="font-editorial text-3xl">{listing?.title||'Private deal'}</h1>{listing&&<p className="text-sm text-muted-foreground">{listing.location} · Asking {formatPrice(Number(listing.price),listing.currency,listing.kind as Kind)}</p>}{deal.offer_amount!=null&&<p className="text-primary mt-1">Current offer {formatAmount(Number(deal.offer_amount),deal.currency)}</p>}</div></div>{isBroker&&<div className="card-warm p-5 mt-4"><p className="field-label">Broker controls</p><div className="flex flex-wrap gap-2 mt-2">{statuses.map(s=><button key={s} onClick={()=>setStatus(s)} className={`px-3 py-1.5 rounded-full text-sm border ${deal.status===s?'bg-primary text-primary-foreground border-primary':'border-border'}`}>{DEAL_STATUS_LABEL[s]}</button>)}</div><div className="mt-4 text-sm"><strong>Private client contact</strong><p className="text-muted-foreground mt-1">{deal.contact_email||'No email'} · {deal.contact_phone||'No phone'}</p></div></div>}
<div className="mt-8 space-y-3">{(messages??[]).map(m=><div key={m.id} className={`max-w-[86%] ${m.sender_id===user.id?'ml-auto':''}`}><div className="rounded-md border border-border bg-background px-4 py-3"><p className="eyebrow">{m.from_broker?BROKER_NAME:m.sender_id===user.id?'You':'Client'}</p><p className="mt-1 whitespace-pre-wrap">{m.body}</p>{m.offer_amount!=null&&<p className="font-editorial text-lg text-primary mt-2">{formatAmount(Number(m.offer_amount),deal.currency)}</p>}</div><p className="text-[11px] text-muted-foreground mt-1">{new Date(m.created_at).toLocaleString()}</p></div>)}</div>
<form onSubmit={send} className="card-warm p-5 mt-8 space-y-3"><h2 className="font-editorial text-xl">{isBroker?'Reply as ApexAnchor':'Message ApexAnchor'}</h2><textarea required className="input-field min-h-28" value={body} onChange={e=>setBody(e.target.value)} placeholder="Write your message…"/><input className="input-field" type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder={`Optional offer (${deal.currency})`}/>{err&&<p className="text-sm text-destructive">{err}</p>}<button className="btn-primary" disabled={busy}>{busy?'Sending…':'Send privately'}</button></form></div>}
