import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { useState } from 'react';
import { z } from 'zod';
import { supabase } from '@/integrations/supabase/client';
import { CATEGORIES, RENTABLE, SELLABLE, type CategoryId, type Kind } from '@/lib/marketplace';
import { CountryCombobox } from '@/components/CountryCombobox';

export const Route = createFileRoute('/_authenticated/sell')({ component: SellPage });
const schema=z.object({title:z.string().trim().min(4).max(120),description:z.string().max(4000).optional(),message:z.string().trim().min(1).max(5000),price:z.coerce.number().nonnegative(),currency:z.string().trim().regex(/^[A-Za-z]{3,4}$/),location:z.string().trim().max(160),image_url:z.string().url().max(2000).optional().or(z.literal(''))});
function SellPage(){const nav=useNavigate();const {user}=Route.useRouteContext();const [kind,setKind]=useState<Kind>('sale');const [category,setCategory]=useState<CategoryId>('house');const [country,setCountry]=useState('');const [saving,setSaving]=useState(false);const [err,setErr]=useState<string|null>(null);const available=kind==='rent'?RENTABLE:SELLABLE;
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setErr(null);const f=new FormData(e.currentTarget);const p=schema.safeParse({title:f.get('title'),description:f.get('description'),message:f.get('message'),price:f.get('price'),currency:f.get('currency')||'USD',location:country, image_url:f.get('image_url')});if(!p.success)return setErr(p.error.issues[0].message);if(!country)return setErr('Choose a country.');setSaving(true);const {data,error}=await supabase.rpc('submit_listing',{p_kind:kind,p_category:category,p_title:p.data.title,p_description:p.data.description??'',p_price:p.data.price,p_currency:p.data.currency.toUpperCase(),p_location:country,p_image_url:p.data.image_url??'',p_message:p.data.message});setSaving(false);if(error)return setErr(error.message);if(!data)return setErr('Could not create the private thread.');void user;nav({to:'/deals/$id',params:{id:data}});}
return <div className="max-w-2xl mx-auto px-5 py-12"><p className="eyebrow">Verified broker channel</p><h1 className="font-editorial text-5xl mt-2">List an asset</h1><p className="text-muted-foreground mt-3">We review your asset, put it on the market, and handle every buyer and every price conversation for you. Your details are never shown publicly.</p><form onSubmit={submit} className="mt-8 space-y-5"><div><label className="field-label">Sale or rent</label><div className="segmented mt-2"><button type="button" onClick={()=>{setKind('sale');if(!SELLABLE.includes(category))setCategory('house')}} className={kind==='sale'?'active':''}>For sale</button><button type="button" onClick={()=>{setKind('rent');if(!RENTABLE.includes(category))setCategory('house')}} className={kind==='rent'?'active':''}>For rent</button></div></div><div><label className="field-label">Category</label><div className="mt-2 flex flex-wrap gap-2">{CATEGORIES.filter(c=>available.includes(c.id)).map(c=><button type="button" key={c.id} onClick={()=>setCategory(c.id)} className={`px-3 py-1.5 rounded-full text-sm border ${category===c.id?'bg-primary text-primary-foreground border-primary':'border-border'}`}>{c.label}</button>)}</div></div><div><label className="field-label">Title</label><input name="title" required className="input-field mt-1" placeholder="Sun-drenched 3-bed near the park"/></div><div><label className="field-label">Description</label><textarea name="description" className="input-field mt-1 min-h-36" placeholder="What makes it special?"/></div><div className="grid grid-cols-3 gap-3"><div className="col-span-2"><label className="field-label">Price {kind==='rent'&&'(per month)'}</label><input name="price" type="number" min="0" step="0.01" required className="input-field mt-1"/></div><div><label className="field-label">Currency</label><input name="currency" defaultValue="USD" maxLength={4} className="input-field mt-1"/></div></div><div><label className="field-label">Country</label><CountryCombobox value={country} onChange={setCountry}/></div><div><label className="field-label">Image URL (optional)</label><input name="image_url" type="url" className="input-field mt-1" placeholder="https://…"/></div><div><label className="field-label">Private message to ApexAnchor</label><textarea name="message" required className="input-field mt-1 min-h-32" placeholder="Tell the broker what you are offering and anything they should know."/></div>{err&&<p className="text-sm text-destructive">{err}</p>}<button disabled={saving} className="btn-primary w-full disabled:opacity-60">{saving?'Submitting…':'Submit privately to ApexAnchor'}</button></form></div>}
