export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = { public: { Tables: {
profiles:{Row:{id:string;display_name:string|null;phone:string|null;avatar_url:string|null;created_at:string;updated_at:string};Insert:{id:string;display_name?:string|null;phone?:string|null;avatar_url?:string|null;created_at?:string;updated_at?:string};Update:{id?:string;display_name?:string|null;phone?:string|null;avatar_url?:string|null;updated_at?:string};Relationships:[]};
user_roles:{Row:{id:string;user_id:string;role:Database['public']['Enums']['app_role'];created_at:string};Insert:{id?:string;user_id:string;role:Database['public']['Enums']['app_role'];created_at?:string};Update:{id?:string;user_id?:string;role?:Database['public']['Enums']['app_role']};Relationships:[]};
listings:{Row:{id:string;owner_id:string;kind:Database['public']['Enums']['listing_kind'];category:Database['public']['Enums']['listing_category'];title:string;description:string;price:number;currency:string;location:string;image_url:string|null;status:Database['public']['Enums']['listing_status'];created_at:string;updated_at:string};Insert:{id?:string;owner_id:string;kind:Database['public']['Enums']['listing_kind'];category:Database['public']['Enums']['listing_category'];title:string;description?:string;price:number;currency?:string;location?:string;image_url?:string|null;status?:Database['public']['Enums']['listing_status'];created_at?:string;updated_at?:string};Update:{id?:string;owner_id?:string;kind?:Database['public']['Enums']['listing_kind'];category?:Database['public']['Enums']['listing_category'];title?:string;description?:string;price?:number;currency?:string;location?:string;image_url?:string|null;status?:Database['public']['Enums']['listing_status'];updated_at?:string};Relationships:[]};
deals:{Row:{id:string;listing_id:string;client_id:string;side:Database['public']['Enums']['deal_side'];status:Database['public']['Enums']['deal_status'];offer_amount:number|null;currency:string;contact_email:string|null;contact_phone:string|null;start_date:string|null;end_date:string|null;created_at:string;updated_at:string};Insert:{id?:string;listing_id:string;client_id:string;side:Database['public']['Enums']['deal_side'];status?:Database['public']['Enums']['deal_status'];offer_amount?:number|null;currency?:string;contact_email?:string|null;contact_phone?:string|null;start_date?:string|null;end_date?:string|null;created_at?:string;updated_at?:string};Update:{id?:string;listing_id?:string;client_id?:string;side?:Database['public']['Enums']['deal_side'];status?:Database['public']['Enums']['deal_status'];offer_amount?:number|null;currency?:string;contact_email?:string|null;contact_phone?:string|null;start_date?:string|null;end_date?:string|null;updated_at?:string};Relationships:[]};
deal_messages:{Row:{id:string;deal_id:string;sender_id:string;from_broker:boolean;body:string;offer_amount:number|null;created_at:string};Insert:{id?:string;deal_id:string;sender_id:string;from_broker:boolean;body:string;offer_amount?:number|null;created_at?:string};Update:{id?:string;deal_id?:string;sender_id?:string;from_broker?:boolean;body?:string;offer_amount?:number|null};Relationships:[]};
}; Views:{[_ in never]:never}; Functions:{has_role:{Args:{_user_id:string;_role:Database['public']['Enums']['app_role']};Returns:boolean};broker_exists:{Args:never;Returns:boolean}}; Enums:{app_role:'broker'|'user';listing_kind:'sale'|'rent';listing_category:'car'|'house'|'land'|'company'|'business_idea'|'office';listing_status:'pending'|'active'|'draft'|'sold'|'archived';deal_side:'buy'|'sell';deal_status:'open'|'negotiating'|'agreed'|'closed'|'declined'}; CompositeTypes:{[_ in never]:never}; } };
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
export type CompositeTypes<T extends never = never> = never;
export const Constants = { public: { Enums: { app_role:['broker','user'],listing_kind:['sale','rent'],listing_category:['car','house','land','company','business_idea','office'],listing_status:['pending','active','draft','sold','archived'],deal_side:['buy','sell'],deal_status:['open','negotiating','agreed','closed','declined'] } } } as const;
